### PR TITLE
Added comment about finding block numbers

### PR DESCRIPTION
**Pull request by gang525**
## Purpose
Literally just one comment to the example file because I was getting confused about what the block number was. There may be a more appropriate place to put this type of clarifying statement though (like MACH-Aero tutorial?).

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
No test needed. It's a comment line

## Checklist

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by akleb — APPROVED** [review]

**Review by sseraj — APPROVED** [review]
This could also be added to the help string, but since you started from this example and others most likely will too, I am fine with adding it here.

**Comment by akleb** [comment]
Why not add it to both the doc string and the example @sseraj ?

**Comment by sseraj** [comment]
> Why not add it to both the ~doc~ help string and the example @sseraj ?

I would not add this specific line to the help string because it only really applies to single pyHyp meshes. The most general way to find the block ID using Tecplot would be: 
1) Load the mesh with `Advanced options > One Tecplot zone per non-poly CGNS zone/solution`
2) Use the Zone Number for the block ID

This method does not rely on Zone Names so it works with overset meshes and non-pyHyp meshes. Maybe we should just update the example and help strings with this instead. What do you think @gang525?

Also, I think it would make sense to add the same descriptions to the overwriteBC example and help strings.

**Comment by gang525** [comment]
My original thought was to add it to the help string but I decided against it because I was thinking of something like `(e.g. block number is domain number from tecplot for volume mesh)`, which isn't general at all. What @sseraj suggests makes sense to me. The help string to find block ID should be as general as possible.

The changes should be made to the example and help string for both overwrite functions IMO.

**Comment by gang525** [comment]
I placed the explanation for finding the blockID in tecplot right before the examples portion in the help strings. I'm open to suggestions if there are better places, but it felt like right before the listed examples flows logically.

**Review by sseraj — APPROVED** [review]
Looks good, thanks!

**Review by akleb — APPROVED** [review]

**Pull request merged**
