### PR TITLE
Renaming options

### PR DESCRIPTION
**Pull request by akleb**
## Purpose
Make the options consistently camelCase for readability. I could not figure out a way to accept fully lowercased options instead of just the camelCase options. It seems that this is easy to do for the arguments passed for an option (using `type=str.lower` instead of `type=str`), but this cannot affect the actual option names. That means that for now this pr is not backward compatible. #37 

## Type of change
What types of change is it?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (non-backwards-compatible fix or feature)
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
ran flake8/black and unittests so I do not think I broke something. 

## Checklist

- [X] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [X] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation

### CODE REVIEW

**Review by sseraj — COMMENTED** [review]
Yes, we should bump the minor version.
 
Other changes:
- `autobc` and `double2d` should also be updated to have the same case as the corresponding function names
- overwriteBCs.sh in the examples should be updated to use camelCase

One other thing that was mentioned in #33 is that it would make sense to rename some options to be more descriptive. I think it makes sense to do that here because we are breaking backwards compatibility anyway.

The ones I can think of are:
```
family
familySubface
familyCopy
remove
```
These should be renamed to have the same name as the underlying function. For example `family` would become `overwriteFamilies`. I'm not sure about the renaming though so I would like to hear more opinions @eirikurj @nwu63

**Comment by marcomangano** [comment]
Agree on everything Sabet wrote, just want to add a question: is this option renaming going to affect any other lab package, or are these options CLI-specific?

**Comment by nwu63** [comment]
I definitely prefer more descriptive names, and having the name start with a verb is nice I think, e.g. `copyFamily` instead of `familyCopy`. Like others have said, if we are breaking backwards compatibility (which isn't a big deal IMO since this is just CLI) then we might as well make sure everything makes sense.

**Comment by nwu63** [comment]
Also, can we make `overwriteBCs.sh` a test?

**Comment by nwu63** [comment]
> There is an equivalent test, but the tests don't use the CLI.

Yeah I know, I'm saying we should test both the underlying library as well as the CLI. Just blinding running the shell script would be step one of that I think.

**Comment by akleb** [comment]
File paths on the CLI test does not feel good, open to better ways of doing it

**Comment by sseraj** [comment]
> File paths on the CLI test does not feel good, open to better ways of doing it

They should use absolute paths instead. See the [pyHyp tests](https://github.com/mdolab/pyhyp/blob/master/reg_tests/test_all_examples.py) for an example on how to do that.

Other than that, I think the names for the `*Grid` options were fine before. The `Grid` part is implied for most of the basic operations. On the other hand, I should have included `extract` and `extractSpecified` in my list of options to change.

**Review by sseraj — APPROVED** [review]
Nice work. If you're planning on working with `cgns_utils` more in the future, I think it makes sense for you to be a maintainer. That will also let you make a new release once this is merged.

**Review by joanibal — APPROVED** [review]

**Pull request merged**
