### PR TITLE
Add example scripts as tests

### PR DESCRIPTION
**Pull request by eirikurj**
## Purpose
This PR adds a glob tests that make sure that the examples (shell scripts) in the `examples` directory are tested and finish execution.

## Expected time until merged
Non-urgent, but should not take more than a week.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by sseraj — COMMENTED** [review]
Does it still make sense to have the `TestCLI` class? Those tests essentially duplicate the examples.

**Comment by marcomangano** [comment]
A good feature of the `testCLI` tests is that they test features individually, while `TestExamples` has all the examples aggregated into a single check - not great for debugging

**Comment by eirikurj** [comment]
@sseraj I see these are having different purposes. `TestCLI` tests the API (and ideally should cover everything), but `TestExamples` is meant to make sure that the examples will actually run, since the examples are meant for end-users to read and show how to use/achieve specific things.
@marcomangano this is something that I thought about also. I opted for this one-and-done test because then you dont need to include anything in the tests if an example is added. However, it did not separate out the tests. To address that, I added parameterized to generate one function per script.

**Review by marcomangano — APPROVED** [review]

**Review by sseraj — APPROVED** [review]
I still think there's some redundancy, but I'm not going to complain about having too many tests.

**Comment by eirikurj** [comment]
Thanks @sseraj, I agree that there is definitely some overlap/redundancy. My concern is that the examples do not necessarily test all the parameters for an option (as they may be simpler than what the option allows for). I think if the examples guarantee we test all options etc., then we can remove the `TestCLI` test. We could try to design tall examples such that they test everything (and at the moment, I think this might be the case), but with more examples it might not be.

**Pull request merged**
