### PR TITLE
Decode in readGrid

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

Since moving to Python 3, there have been issues with the strings coming out of readGrid. We have been adding decode calls in several places, but I think it is better to just decode everything in readGrid. Strictly speaking, this is a breaking change. However, this only affects people using readGrid directly in their scripts, and the fix is easy (removing any decode calls on already decoded strings).

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

The existing tests still pass after removing the decode calls.

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by joanibal — APPROVED** [review]

**Comment by joanibal** [comment]
Good change

**Comment by sseraj** [comment]
@eirikurj @marcomangano It would be great to have this PR merged in soon. It's blocking #47 and another PR I want to open on IDWarp.

**Review by eirikurj — APPROVED** [review]
@sseraj, the changes look good. I pushed one commit, one place that was missing.

**Comment by sseraj** [comment]
Thanks @eirikurj!

**Review by joanibal — APPROVED** [review]

**Pull request merged**
